export const PRODUCTS = [
  { id: 'p1', name: 'HP ProBook 450 G10', cat: 'PC Portables', price: 425000, stock: 7, code: 'NGS-1041', image: '/products/hp-probook-450-g10.jpg',
    blurb: "Le poste de travail bureautique que nous déployons le plus : i5 13e génération, 16 Go, clavier AZERTY, châssis testé en atelier avant livraison.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-1335U' }, { k: 'Mémoire', v: '16 Go DDR4' }, { k: 'Stockage', v: 'SSD NVMe 512 Go' }, { k: 'Écran', v: '15,6" Full HD antireflet' }, { k: 'Garantie', v: '12 mois atelier NG' }] },
  { id: 'p2', name: 'Dell OptiPlex 7010 SFF', cat: 'PC Bureaux', price: 310000, stock: 4, code: 'NGS-2210', image: '/products/dell-optiplex-7010-sff.jpg',
    blurb: "Unité centrale compacte pour comptabilité et caisse, alimentation 300 W remplaçable, quatre ports USB en façade.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-13500' }, { k: 'Mémoire', v: '8 Go extensible 64 Go' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Format', v: 'Small Form Factor' }] },
  { id: 'p3', name: 'Lenovo ThinkPad T14 Gen 4', cat: 'PC Portables', price: 520000, stock: 2, code: 'NGS-1077', image: '/products/lenovo-thinkpad-t14-gen4.jpg',
    blurb: "Le portable des équipes en déplacement : clavier référence, charnières testées 25 000 cycles, station d'accueil compatible.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7-1355U' }, { k: 'Mémoire', v: '16 Go' }, { k: 'Stockage', v: 'SSD NVMe 1 To' }, { k: 'Autonomie', v: '9 h en usage bureautique' }] },
  { id: 'p4', name: 'SSD NVMe Samsung 980 1 To', cat: 'Composantes', price: 62000, stock: 18, code: 'NGS-3301', image: '/products/ssd-nvme-samsung-980.jpg',
    blurb: "La mise à niveau la plus rentable sur un poste lent. Clonage du système inclus en atelier.",
    specs: [{ k: 'Interface', v: 'PCIe 3.0 x4 NVMe' }, { k: 'Lecture', v: '3 500 Mo/s' }, { k: 'Endurance', v: '600 To écrits' }] },
  { id: 'p5', name: 'Mémoire DDR4 16 Go Kingston', cat: 'Composantes', price: 34000, stock: 25, code: 'NGS-3318', image: '/products/ram-ddr4-16go-kingston.png',
    blurb: "Barrette 3200 MHz compatible avec la majorité des postes de bureau que nous vendons.",
    specs: [{ k: 'Capacité', v: '16 Go' }, { k: 'Fréquence', v: '3200 MHz' }, { k: 'Format', v: 'DIMM' }] },
  { id: 'p6', name: 'HP LaserJet Pro M211d', cat: 'Imprimantes', price: 118000, stock: 6, code: 'NGS-4102', image: '/products/hp-laserjet-pro-m211d.png',
    blurb: "Laser monochrome recto-verso automatique, 29 pages/minute, toner disponible en boutique.",
    specs: [{ k: 'Technologie', v: 'Laser monochrome' }, { k: 'Vitesse', v: '29 ppm' }, { k: 'Recto-verso', v: 'Automatique' }] },
  { id: 'p7', name: 'Epson EcoTank L3260', cat: 'Imprimantes', price: 145000, stock: 3, code: 'NGS-4119', image: '/products/epson-ecotank-l3260.jpg',
    blurb: "Multifonction à réservoirs : le coût par page le plus bas du catalogue, Wi-Fi direct.",
    specs: [{ k: 'Fonctions', v: 'Impression, copie, scan' }, { k: 'Encre', v: 'Réservoirs rechargeables' }, { k: 'Connexion', v: 'Wi-Fi + USB' }] },
  { id: 'p93', name: 'Canon i-SENSYS MF657Cdw', cat: 'Imprimantes', price: 385000, stock: 4, code: 'NGS-4120', image: '/products/canon-isensys-mf657cdw.png',
    blurb: "Multifonction laser couleur professionnelle, écran tactile, idéale pour un bureau avec impressions fréquentes.",
    specs: [{ k: 'Technologie', v: 'Laser couleur' }, { k: 'Fonctions', v: 'Impression, copie, scan, fax' }, { k: 'Écran', v: 'Tactile couleur' }, { k: 'Connexion', v: 'Wi-Fi + réseau' }] },
  { id: 'p94', name: 'HP LaserJet MFP 137fnw', cat: 'Imprimantes', price: 195000, stock: 6, code: 'NGS-4121', image: '/products/hp-laserjet-mfp-137fnw.png',
    blurb: "Laser monochrome tout-en-un avec fax et chargeur automatique de documents, fiable pour un usage bureautique quotidien.",
    specs: [{ k: 'Technologie', v: 'Laser monochrome' }, { k: 'Fonctions', v: 'Impression, copie, scan, fax' }, { k: 'Chargeur', v: 'ADF inclus' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p95', name: 'Canon PIXMA G2420', cat: 'Imprimantes', price: 135000, stock: 8, code: 'NGS-4122', image: '/products/canon-pixma-g2420.webp',
    blurb: "Multifonction à réservoirs compacte, coût par page très bas, idéale pour un usage familial ou petit bureau.",
    specs: [{ k: 'Technologie', v: 'Jet d\'encre à réservoirs' }, { k: 'Fonctions', v: 'Impression, copie, scan' }, { k: 'Connexion', v: 'USB' }] },
  { id: 'p96', name: 'Canon PIXMA G3460', cat: 'Imprimantes', price: 165000, stock: 5, code: 'NGS-4123', image: '/products/canon-pixma-g3460.png',
    blurb: "Multifonction à réservoirs avec chargeur de documents, Wi-Fi intégré, pour un volume d'impression plus soutenu.",
    specs: [{ k: 'Technologie', v: 'Jet d\'encre à réservoirs' }, { k: 'Fonctions', v: 'Impression, copie, scan' }, { k: 'Chargeur', v: 'ADF inclus' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p97', name: 'HP DeskJet 2710', cat: 'Imprimantes', price: 78000, stock: 10, code: 'NGS-4124', image: '/products/hp-deskjet-2710.jpg',
    blurb: "Multifonction jet d'encre couleur compacte et économique, connexion Wi-Fi pour l'impression depuis mobile.",
    specs: [{ k: 'Technologie', v: 'Jet d\'encre couleur' }, { k: 'Fonctions', v: 'Impression, copie, scan' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p98', name: 'Epson EcoTank L1110', cat: 'Imprimantes', price: 98000, stock: 8, code: 'NGS-4125', image: '/products/epson-ecotank-l1110.webp',
    blurb: "Imprimante mono-fonction à réservoirs, très faible coût à la page, idéale pour de gros volumes d'impression.",
    specs: [{ k: 'Technologie', v: 'Jet d\'encre à réservoirs' }, { k: 'Fonctions', v: 'Impression seule' }, { k: 'Connexion', v: 'USB' }] },
  { id: 'p99', name: 'Canon i-SENSYS LBP113w', cat: 'Imprimantes', price: 92000, stock: 9, code: 'NGS-4126', image: '/products/canon-isensys-lbp113w.png',
    blurb: "Imprimante laser monochrome compacte avec Wi-Fi, format idéal pour un poste individuel.",
    specs: [{ k: 'Technologie', v: 'Laser monochrome' }, { k: 'Fonctions', v: 'Impression seule' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p100', name: 'Canon PIXMA G3410', cat: 'Imprimantes', price: 155000, stock: 6, code: 'NGS-4127', image: '/products/canon-pixma-g3410.jpg',
    blurb: "Multifonction à réservoirs avec Wi-Fi, bon compromis entre coût d'achat et coût d'usage.",
    specs: [{ k: 'Technologie', v: 'Jet d\'encre à réservoirs' }, { k: 'Fonctions', v: 'Impression, copie, scan' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p101', name: 'HP Laser 107a', cat: 'Imprimantes', price: 75000, stock: 10, code: 'NGS-4128', image: '/products/hp-laser-107a.jpg',
    blurb: "Imprimante laser monochrome mono-fonction, simple et fiable pour un poste d'appoint.",
    specs: [{ k: 'Technologie', v: 'Laser monochrome' }, { k: 'Fonctions', v: 'Impression seule' }, { k: 'Connexion', v: 'USB' }] },
  { id: 'p102', name: 'HP LaserJet MFP M234sdw', cat: 'Imprimantes', price: 210000, stock: 6, code: 'NGS-4129', image: '/products/hp-laserjet-mfp-m234sdw.jpg',
    blurb: "Multifonction laser monochrome avec recto-verso automatique, adaptée à un usage bureautique intensif.",
    specs: [{ k: 'Technologie', v: 'Laser monochrome' }, { k: 'Fonctions', v: 'Impression, copie, scan' }, { k: 'Recto-verso', v: 'Automatique' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p103', name: 'Canon PIXMA G4470', cat: 'Imprimantes', price: 225000, stock: 4, code: 'NGS-4130', image: '/products/canon-pixma-g4470.jpg',
    blurb: "Multifonction à réservoirs haut de gamme avec fax et chargeur de documents, pour un usage professionnel soutenu.",
    specs: [{ k: 'Technologie', v: 'Jet d\'encre à réservoirs' }, { k: 'Fonctions', v: 'Impression, copie, scan, fax' }, { k: 'Chargeur', v: 'ADF inclus' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p104', name: 'HP Smart Tank 585', cat: 'Imprimantes', price: 175000, stock: 6, code: 'NGS-4131', image: '/products/hp-smart-tank-585.jpg',
    blurb: "Multifonction à réservoirs avec Wi-Fi et application mobile HP Smart, design compact.",
    specs: [{ k: 'Technologie', v: 'Jet d\'encre à réservoirs' }, { k: 'Fonctions', v: 'Impression, copie, scan' }, { k: 'Connexion', v: 'Wi-Fi' }] },
  { id: 'p8', name: 'Switch TP-Link 8 ports Gigabit', cat: 'Réseaux', price: 28000, stock: 14, code: 'NGS-5203', image: '/products/switch-tplink-8ports.jpg',
    blurb: "Boîtier métal non administrable, alimentation externe, idéal petite baie de bureau.",
    specs: [{ k: 'Ports', v: '8 × 10/100/1000' }, { k: 'Boîtier', v: 'Métal, sans ventilateur' }] },
  { id: 'p9', name: 'Routeur Wi-Fi 6 Archer AX23', cat: 'Réseaux', price: 47000, stock: 9, code: 'NGS-5211', image: '/products/routeur-tplink-archer-ax23.jpg',
    blurb: "Couvre un plateau de bureaux de 120 m², quatre antennes, gestion depuis mobile.",
    specs: [{ k: 'Norme', v: 'Wi-Fi 6 AX1800' }, { k: 'Ports', v: '4 LAN Gigabit' }] },
  { id: 'p105', name: 'Routeur mobile 4G/5G LTE Pocket WiFi', cat: 'Réseaux', price: 45000, stock: 10, code: 'NGS-5212', image: '/products/routeur-mobile-lte-pocket.jpg',
    blurb: "Routeur de poche 4G/5G, écran de contrôle intégré, pour une connexion mobile partagée jusqu'à plusieurs appareils.",
    specs: [{ k: 'Réseau', v: '4G/5G LTE' }, { k: 'Écran', v: 'Écran couleur intégré' }] },
  { id: 'p106', name: 'Carte réseau PCIe Gigabit TP-Link TG-3468', cat: 'Réseaux', price: 12000, stock: 15, code: 'NGS-5213', image: '/products/carte-reseau-pcie-tplink-tg3468.jpg',
    blurb: "Ajoute un port Ethernet Gigabit à une tour PC dépourvue de réseau filaire ou en panne.",
    specs: [{ k: 'Interface', v: 'PCI Express' }, { k: 'Réseau', v: 'Gigabit Ethernet' }] },
  { id: 'p107', name: 'Routeur mobile 4G Huawei E5573', cat: 'Réseaux', price: 38000, stock: 10, code: 'NGS-5214', image: '/products/routeur-mobile-huawei-e5573.jpg',
    blurb: "Routeur 4G de poche fiable et compact, partage la connexion d'une carte SIM à plusieurs appareils.",
    specs: [{ k: 'Réseau', v: '4G LTE' }, { k: 'Format', v: 'Portable, batterie intégrée' }] },
  { id: 'p108', name: 'Routeur Wi-Fi AC1200 TP-Link Archer C50', cat: 'Réseaux', price: 32000, stock: 12, code: 'NGS-5215', image: '/products/routeur-tplink-archer-c50.jpg',
    blurb: "Routeur double bande quatre antennes, bonne couverture pour un appartement ou un petit bureau.",
    specs: [{ k: 'Norme', v: 'AC1200 double bande' }, { k: 'Antennes', v: '4 × 5 dBi' }] },
  { id: 'p109', name: 'Répéteur Wi-Fi 300 Mbps', cat: 'Réseaux', price: 12000, stock: 15, code: 'NGS-5216', image: '/products/repeteur-wifi-300mbps.jpg',
    blurb: "Prolonge la portée du réseau Wi-Fi jusqu'à 100 m, se branche directement sur une prise murale.",
    specs: [{ k: 'Débit', v: 'Jusqu\'à 300 Mbps' }, { k: 'Portée', v: 'Jusqu\'à 100 m' }] },
  { id: 'p110', name: 'Clé Wi-Fi USB N150 avec antenne', cat: 'Réseaux', price: 7000, stock: 20, code: 'NGS-5217', image: '/products/cle-wifi-usb-antenne.jpg',
    blurb: "Ajoute le Wi-Fi à un poste de bureau qui n'en dispose pas, antenne orientable pour une meilleure réception.",
    specs: [{ k: 'Débit', v: 'Jusqu\'à 150 Mbps' }, { k: 'Interface', v: 'USB' }] },
  { id: 'p111', name: 'Switch 5 ports TP-Link LiteWave LS1005', cat: 'Réseaux', price: 15000, stock: 15, code: 'NGS-5218', image: '/products/switch-tplink-ls1005.jpg',
    blurb: "Switch compact plug-and-play sans ventilateur, idéal pour étendre un petit réseau filaire.",
    specs: [{ k: 'Ports', v: '5 × 10/100 Mbps' }, { k: 'Boîtier', v: 'Sans ventilateur' }] },
  { id: 'p112', name: 'Clé Wi-Fi Nano USB TP-Link TL-WN725N', cat: 'Réseaux', price: 6500, stock: 20, code: 'NGS-5219', image: '/products/cle-wifi-nano-tplink-wn725n.jpg',
    blurb: "Format ultra-compact quasi invisible une fois branché, idéal sur un poste portable ou en façade de tour.",
    specs: [{ k: 'Débit', v: 'Jusqu\'à 150 Mbps' }, { k: 'Format', v: 'Nano USB' }] },
  { id: 'p113', name: 'Routeur mobile 4G Airtel Pocket WiFi M30 Pro', cat: 'Réseaux', price: 42000, stock: 8, code: 'NGS-5220', image: '/products/routeur-mobile-airtel-m30pro.jpg',
    blurb: "Pack complet avec batterie de rechange, pour une connexion mobile 4G nomade toute la journée.",
    specs: [{ k: 'Réseau', v: '4G LTE' }, { k: 'Accessoires', v: 'Batterie de rechange incluse' }] },
  { id: 'p114', name: 'Routeur mobile 5G+ LTE Mobile WiFi', cat: 'Réseaux', price: 55000, stock: 8, code: 'NGS-5221', image: '/products/routeur-mobile-5g-lte.jpg',
    blurb: "Routeur de poche nouvelle génération, batterie 3000 mAh, port USB-C, pour les débits 5G les plus élevés.",
    specs: [{ k: 'Réseau', v: '4G/5G LTE' }, { k: 'Batterie', v: '3000 mAh, USB-C' }] },
  { id: 'p115', name: 'Répéteur Wi-Fi 4 antennes', cat: 'Réseaux', price: 14000, stock: 12, code: 'NGS-5222', image: '/products/repeteur-wifi-4antennes.jpg',
    blurb: "Répéteur mural quatre antennes pour une portée renforcée, port Ethernet et prise EU intégrée.",
    specs: [{ k: 'Antennes', v: '4' }, { k: 'Ports', v: '1 × LAN' }] },
  { id: 'p116', name: 'Répéteur Wi-Fi avec port LAN', cat: 'Réseaux', price: 13000, stock: 12, code: 'NGS-5223', image: '/products/repeteur-wifi-lan.jpg',
    blurb: "Répéteur compact avec bouton WPS et port LAN, installation en quelques secondes sur prise murale.",
    specs: [{ k: 'Configuration', v: 'Bouton WPS' }, { k: 'Ports', v: '1 × LAN' }] },
  { id: 'p10', name: 'Onduleur APC 650 VA', cat: 'Composantes', price: 39000, stock: 11, code: 'NGS-3340', image: '/products/onduleur-apc-650va.jpg',
    blurb: "Protège caisse et poste comptabilité des coupures et des micro-coupures secteur.",
    specs: [{ k: 'Puissance', v: '650 VA / 360 W' }, { k: 'Autonomie', v: '12 min à demi-charge' }] },

  { id: 'p11', name: 'Samsung Galaxy A15 128 Go', cat: 'Téléphones & Tablettes', price: 145000, stock: 12, code: 'NGS-6001', image: '/products/samsung-galaxy-a15.jpg',
    blurb: "Smartphone Android polyvalent, écran 6,5\" Super AMOLED, batterie 5000 mAh, idéal pour un usage professionnel comme personnel.",
    specs: [{ k: 'Écran', v: '6,5" Super AMOLED' }, { k: 'Stockage', v: '128 Go' }, { k: 'Mémoire', v: '4 Go RAM' }, { k: 'Batterie', v: '5000 mAh' }] },
  { id: 'p12', name: 'Tablette Lenovo Tab M10 Plus', cat: 'Téléphones & Tablettes', price: 98000, stock: 8, code: 'NGS-6015', image: '/products/tablette-lenovo-tab-m10-plus.png',
    blurb: "Tablette 10,6 pouces pour la prise de notes, la lecture de documents et les visioconférences en déplacement.",
    specs: [{ k: 'Écran', v: '10,6" Full HD' }, { k: 'Stockage', v: '64 Go' }, { k: 'Connectivité', v: 'Wi-Fi' }] },
  { id: 'p117', name: 'Tecno Spark', cat: 'Téléphones & Tablettes', price: 95000, stock: 12, code: 'NGS-6016', image: '/products/tecno-spark-cameo.jpg',
    blurb: "Smartphone abordable à l'anneau lumineux caractéristique autour du module photo.",
    specs: [{ k: 'Écran', v: '6,6" HD+' }, { k: 'Mémoire', v: '4 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Caméra', v: 'Triple capteur' }] },
  { id: 'p118', name: 'Tecno Camon 20 Pro', cat: 'Téléphones & Tablettes', price: 165000, stock: 8, code: 'NGS-6017', image: '/products/tecno-camon-argent.jpg',
    blurb: "Milieu de gamme photo, écran AMOLED fluide, dos dégradé argent/noir.",
    specs: [{ k: 'Écran', v: '6,7" AMOLED' }, { k: 'Mémoire', v: '8 Go RAM' }, { k: 'Stockage', v: '256 Go' }, { k: 'Caméra', v: 'Triple 64 MP' }] },
  { id: 'p119', name: 'Samsung Galaxy A55 5G', cat: 'Téléphones & Tablettes', price: 285000, stock: 8, code: 'NGS-6018', image: '/products/samsung-galaxy-a55.jpg',
    blurb: "Milieu de gamme Samsung récent, écran Super AMOLED, compatible réseaux 5G.",
    specs: [{ k: 'Écran', v: '6,6" Super AMOLED' }, { k: 'Mémoire', v: '8 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Réseau', v: '5G' }] },
  { id: 'p120', name: 'Samsung Galaxy A14 5G', cat: 'Téléphones & Tablettes', price: 145000, stock: 10, code: 'NGS-6019', image: '/products/samsung-galaxy-a14.jpg',
    blurb: "Entrée de gamme Samsung compatible 5G, bon rapport qualité-prix pour un usage courant.",
    specs: [{ k: 'Écran', v: '6,6" PLS LCD' }, { k: 'Mémoire', v: '4 Go RAM' }, { k: 'Stockage', v: '64 Go' }, { k: 'Réseau', v: '5G' }] },
  { id: 'p121', name: 'Samsung Duos (téléphone classique)', cat: 'Téléphones & Tablettes', price: 22000, stock: 20, code: 'NGS-6020', image: '/products/samsung-duos-basique.jpg',
    blurb: "Téléphone à touches double SIM, batterie longue durée, pour un usage simple ou en secours.",
    specs: [{ k: 'Écran', v: '2,4" couleur' }, { k: 'SIM', v: 'Double SIM' }, { k: 'Type', v: 'Téléphone classique' }] },
  { id: 'p122', name: 'Huawei P Smart 2021', cat: 'Téléphones & Tablettes', price: 118000, stock: 9, code: 'NGS-6021', image: '/products/huawei-p-smart-2021.jpg',
    blurb: "Smartphone polyvalent avec quadruple capteur photo et grand écran FHD+.",
    specs: [{ k: 'Écran', v: '6,67" FHD+' }, { k: 'Mémoire', v: '4 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Caméra', v: 'Quadruple 48 MP' }] },
  { id: 'p123', name: 'Huawei P30 Pro', cat: 'Téléphones & Tablettes', price: 235000, stock: 5, code: 'NGS-6022', image: '/products/huawei-p30-pro.jpg',
    blurb: "Haut de gamme photo signé Leica, écran OLED incurvé, reconnaissance faciale.",
    specs: [{ k: 'Écran', v: '6,47" OLED incurvé' }, { k: 'Mémoire', v: '8 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Caméra', v: 'Quadruple Leica' }] },
  { id: 'p124', name: 'Honor X', cat: 'Téléphones & Tablettes', price: 108000, stock: 10, code: 'NGS-6023', image: '/products/honor-x-vert.jpg',
    blurb: "Smartphone accessible avec caméra assistée par IA, écran HD+ confortable.",
    specs: [{ k: 'Écran', v: '6,56" HD+' }, { k: 'Mémoire', v: '4 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Caméra', v: 'Assistée IA' }] },
  { id: 'p125', name: 'Honor X7b', cat: 'Téléphones & Tablettes', price: 135000, stock: 9, code: 'NGS-6024', image: '/products/honor-x7b.jpg',
    blurb: "Grand capteur photo 108 MP, écran FHD+ 6,7 pouces, autonomie confortable.",
    specs: [{ k: 'Écran', v: '6,7" FHD+' }, { k: 'Mémoire', v: '8 Go RAM' }, { k: 'Stockage', v: '256 Go' }, { k: 'Caméra', v: '108 MP' }] },
  { id: 'p126', name: 'Infinix Hot 50', cat: 'Téléphones & Tablettes', price: 92000, stock: 12, code: 'NGS-6025', image: '/products/infinix-hot-50.jpg',
    blurb: "Bon rapport autonomie/prix, charge rapide 18 W, caméra 50 MP.",
    specs: [{ k: 'Mémoire', v: '8 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Batterie', v: '5000 mAh, charge 18 W' }, { k: 'Caméra', v: '50 MP' }] },
  { id: 'p127', name: 'Redmi (série verte)', cat: 'Téléphones & Tablettes', price: 128000, stock: 10, code: 'NGS-6026', image: '/products/redmi-vert.jpg',
    blurb: "Smartphone Redmi polyvalent, module photo quadruple, grand écran.",
    specs: [{ k: 'Écran', v: '6,7"' }, { k: 'Mémoire', v: '6 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Caméra', v: 'Quadruple capteur' }] },
  { id: 'p128', name: 'Redmi Note 13', cat: 'Téléphones & Tablettes', price: 155000, stock: 9, code: 'NGS-6027', image: '/products/redmi-note-13.jpg',
    blurb: "Écran AMOLED fluide et capteur photo 108 MP, très bon rapport qualité-prix.",
    specs: [{ k: 'Écran', v: '6,67" AMOLED' }, { k: 'Mémoire', v: '8 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Caméra', v: '108 MP' }] },
  { id: 'p129', name: 'Samsung Galaxy A16', cat: 'Téléphones & Tablettes', price: 165000, stock: 10, code: 'NGS-6028', image: '/products/samsung-galaxy-a16.jpg',
    blurb: "Écran Super AMOLED confortable, finition métallique, pour un usage quotidien fluide.",
    specs: [{ k: 'Écran', v: '6,7" Super AMOLED' }, { k: 'Mémoire', v: '4 Go RAM' }, { k: 'Stockage', v: '128 Go' }] },
  { id: 'p130', name: 'Tecno Spark 30c', cat: 'Téléphones & Tablettes', price: 98000, stock: 12, code: 'NGS-6029', image: '/products/tecno-spark-30c.jpg',
    blurb: "Charge rapide et grand écran 6,67 pouces, caméra 50 MP pour un smartphone abordable.",
    specs: [{ k: 'Écran', v: '6,67"' }, { k: 'Mémoire', v: '8 Go RAM (+12 Go étendue)' }, { k: 'Stockage', v: '128 Go' }, { k: 'Batterie', v: '5000 mAh, charge rapide' }] },
  { id: 'p131', name: 'Tecno Spark (bleu nuit)', cat: 'Téléphones & Tablettes', price: 88000, stock: 12, code: 'NGS-6030', image: '/products/tecno-spark-bleu.jpg',
    blurb: "Version économique de la gamme Spark, finition bleu nuit, pour un premier smartphone.",
    specs: [{ k: 'Écran', v: '6,6"' }, { k: 'Mémoire', v: '4 Go RAM' }, { k: 'Stockage', v: '128 Go' }, { k: 'Caméra', v: 'Double capteur' }] },
  { id: 'p132', name: 'Tecno Camon (teal)', cat: 'Téléphones & Tablettes', price: 175000, stock: 7, code: 'NGS-6031', image: '/products/tecno-camon-teal.jpg',
    blurb: "Dos incurvé et finition teal élégante, écran AMOLED, module photo triple 64 MP.",
    specs: [{ k: 'Écran', v: '6,7" AMOLED incurvé' }, { k: 'Mémoire', v: '8 Go RAM' }, { k: 'Stockage', v: '256 Go' }, { k: 'Caméra', v: 'Triple 64 MP' }] },

  { id: 'p13', name: 'Réfrigérateur Table-Top Hisense 120 L', cat: 'Électroménager', price: 165000, stock: 5, code: 'NGS-7002', image: '/products/refrigerateur-hisense-120l.jpg',
    blurb: "Réfrigérateur compact pour bureau ou petite cuisine, faible consommation, compartiment congélateur intégré.",
    specs: [{ k: 'Capacité', v: '120 L' }, { k: 'Classe énergétique', v: 'A+' }, { k: 'Type', v: 'Table-top' }] },
  { id: 'p14', name: 'Climatiseur Split Inverter 1,5 CV', cat: 'Électroménager', price: 285000, stock: 3, code: 'NGS-7020', image: '/products/climatiseur-split-inverter-1-5cv.jpg',
    blurb: "Climatiseur split inverter silencieux pour bureau ou salle serveur, installation incluse à Abidjan.",
    specs: [{ k: 'Puissance', v: '1,5 CV' }, { k: 'Technologie', v: 'Inverter' }, { k: 'Gaz réfrigérant', v: 'R32' }] },

  { id: 'p15', name: 'Manette sans fil PC/Console', cat: 'Gaming', price: 22000, stock: 16, code: 'NGS-8003', image: '/products/manette-sans-fil-pc-console.jpg',
    blurb: "Manette sans fil compatible PC et consoles, autonomie 20 h, vibration double moteur.",
    specs: [{ k: 'Connexion', v: 'Bluetooth + USB' }, { k: 'Autonomie', v: '20 h' }, { k: 'Compatibilité', v: 'PC / Android / Consoles' }] },
  { id: 'p16', name: 'Casque Gaming RGB filaire', cat: 'Gaming', price: 18000, stock: 10, code: 'NGS-8021', image: '/products/casque-gaming-rgb.jpg',
    blurb: "Casque gaming avec micro amovible, son surround virtuel 7.1, éclairage RGB.",
    specs: [{ k: 'Son', v: 'Surround 7.1 virtuel' }, { k: 'Micro', v: 'Amovible' }, { k: 'Connexion', v: 'USB / Jack 3,5 mm' }] },

  { id: 'p17', name: 'TV LED 43" Full HD', cat: 'TV & Audio', price: 175000, stock: 6, code: 'NGS-9101', image: '/products/tv-led-43-fullhd.jpg',
    blurb: "Téléviseur LED 43 pouces Full HD, idéal salle d'attente ou accueil boutique, ports HDMI et USB multiples.",
    specs: [{ k: 'Taille', v: '43"' }, { k: 'Résolution', v: 'Full HD 1920×1080' }, { k: 'Ports', v: '3× HDMI, 2× USB' }] },
  { id: 'p18', name: 'Barre de son Bluetooth 2.1', cat: 'TV & Audio', price: 45000, stock: 9, code: 'NGS-9115', image: '/products/barre-son-bluetooth.jpg',
    blurb: "Barre de son compacte avec caisson de basses, connexion Bluetooth et optique, idéale salle de réunion.",
    specs: [{ k: 'Canaux', v: '2.1' }, { k: 'Connexion', v: 'Bluetooth / Optique / AUX' }, { k: 'Puissance', v: '60 W RMS' }] },

  { id: 'p19', name: 'HP ProDesk 400 G4 + écran 20"', cat: 'PC Bureaux', price: 295000, stock: 6, code: 'NGS-2211', image: '/products/hp-prodesk-400g4.jpg',
    blurb: "Pack complet unité centrale + écran HP, prêt à brancher pour un poste bureautique ou comptabilité.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-7500' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Écran', v: '20" HP inclus' }] },
  { id: 'p20', name: 'HP Pro Tower 290 G9 + écran 24"', cat: 'PC Bureaux', price: 385000, stock: 4, code: 'NGS-2212', image: '/products/hp-pro-tower-290.jpg',
    blurb: "Modèle récent, châssis compact, idéal pour un remplacement de parc avec écran Full HD 24 pouces inclus.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-12500' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'SSD NVMe 512 Go' }, { k: 'Écran', v: '24" HP inclus' }] },
  { id: 'p21', name: 'HP ProDesk 400 G2 + écran 19"', cat: 'PC Bureaux', price: 245000, stock: 5, code: 'NGS-2213', image: '/products/hp-prodesk-400g2.jpg',
    blurb: "Pack économique reconditionné atelier, testé et garanti, pour poste d'accueil ou de saisie.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-6500' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'HDD 500 Go' }, { k: 'Écran', v: '19" HP inclus' }] },
  { id: 'p22', name: 'HP ProDesk 400 G5 + écran HP V214a', cat: 'PC Bureaux', price: 275000, stock: 7, code: 'NGS-2214', image: '/products/hp-prodesk-v214a.jpg',
    blurb: "Format compact avec écran V214a 20 pouces, bon rapport qualité-prix pour un poste bureautique standard.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-9500' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Écran', v: '20" HP V214a inclus' }] },
  { id: 'p23', name: 'Dell OptiPlex 3080 + écran + clavier/souris', cat: 'PC Bureaux', price: 320000, stock: 6, code: 'NGS-2215', image: '/products/dell-optiplex-3080-kit.jpg',
    blurb: "Pack complet Dell prêt à l'emploi : unité centrale, écran, clavier et souris filaires inclus.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-10500' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Accessoires', v: 'Écran + clavier/souris inclus' }] },
  { id: 'p24', name: 'HP Desktop Pro + écran 21,5"', cat: 'PC Bureaux', price: 305000, stock: 5, code: 'NGS-2216', image: '/products/hp-desktop-pro.jpg',
    blurb: "Configuration équilibrée pour la gestion commerciale et la bureautique multi-fenêtres.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-10500' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Écran', v: '21,5" HP inclus' }] },
  { id: 'p25', name: 'HP All-in-One 22 pouces', cat: 'PC Bureaux', price: 265000, stock: 4, code: 'NGS-2217', image: '/products/hp-aio-22.jpg',
    blurb: "Tout-en-un compact, clavier et souris inclus, encombrement réduit pour un poste d'accueil.",
    specs: [{ k: 'Processeur', v: 'Intel Core i3-10110U' }, { k: 'Mémoire', v: '4 Go DDR4' }, { k: 'Stockage', v: 'HDD 1 To' }, { k: 'Écran', v: '21,5" Full HD intégré' }] },
  { id: 'p26', name: 'HP All-in-One 24 pouces', cat: 'PC Bureaux', price: 425000, stock: 3, code: 'NGS-2218', image: '/products/hp-aio-24.jpg',
    blurb: "Grand écran intégré, design épuré, clavier et souris sans fil inclus pour un bureau de direction.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-1235U' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '23,8" Full HD intégré' }] },
  { id: 'p27', name: 'Dell OptiPlex 3080 (unité seule)', cat: 'PC Bureaux', price: 245000, stock: 8, code: 'NGS-2219', image: '/products/dell-optiplex-3080.jpg',
    blurb: "Unité centrale seule, format tour compacte, connectique complète en façade et à l'arrière.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-10500' }, { k: 'Mémoire', v: '8 Go DDR4' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Format', v: 'Tour compacte' }] },
  { id: 'p28', name: 'Lenovo V50t + écran ThinkVision 21,5"', cat: 'PC Bureaux', price: 235000, stock: 9, code: 'NGS-2220', image: '/products/lenovo-v50t.jpg',
    blurb: "Pack Lenovo complet avec écran, clavier et souris, entrée de gamme fiable pour la bureautique courante.",
    specs: [{ k: 'Processeur', v: 'Intel Core i3' }, { k: 'Mémoire', v: '4 Go DDR4' }, { k: 'Stockage', v: 'HDD 1 To' }, { k: 'Écran', v: '21,5" ThinkVision inclus' }] },

  { id: 'p29', name: 'Dell Latitude 5440', cat: 'PC Portables', price: 620000, stock: 5, code: 'NGS-1042', image: '/products/dell-latitude-5440.jpg',
    blurb: "Ultrabook professionnel 14 pouces, châssis renforcé, webcam avec cache confidentialité, pour cadres en déplacement.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7' }, { k: 'Mémoire', v: '16 Go' }, { k: 'Stockage', v: 'SSD NVMe 512 Go' }, { k: 'Écran', v: '14" Full HD' }] },
  { id: 'p30', name: 'PC Portable Gaming MSI Core i7', cat: 'PC Portables', price: 950000, stock: 3, code: 'NGS-1043', image: '/products/msi-gaming-i7.jpg',
    blurb: "Machine gaming 15,6 pouces, clavier rétroéclairé RGB, carte graphique dédiée pour le jeu et la création.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7' }, { k: 'Carte graphique', v: 'GPU dédiée RTX' }, { k: 'Mémoire', v: '16 Go' }, { k: 'Stockage', v: 'SSD NVMe 512 Go' }] },
  { id: 'p31', name: 'Lenovo ThinkPad E14 Gen 4 — 16 Go', cat: 'PC Portables', price: 580000, stock: 6, code: 'NGS-1044', image: '/products/lenovo-thinkpad-e14-1.jpg',
    blurb: "ThinkPad professionnel 14 pouces sous Windows 11, clavier référence, châssis résistant aux chocs.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7' }, { k: 'Mémoire', v: '16 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '14" WUXGA' }] },
  { id: 'p32', name: 'Lenovo ThinkPad E14 Gen 4 — 32 Go', cat: 'PC Portables', price: 680000, stock: 4, code: 'NGS-1045', image: '/products/lenovo-thinkpad-e14-2.jpg',
    blurb: "Même châssis ThinkPad E14, configuration renforcée en mémoire pour la conception et le multitâche intensif.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7' }, { k: 'Mémoire', v: '32 Go' }, { k: 'Stockage', v: 'SSD 1 To' }, { k: 'Écran', v: '14" WUXGA' }] },
  { id: 'p33', name: 'HP 15 Core i7 13e génération', cat: 'PC Portables', price: 545000, stock: 6, code: 'NGS-1046', image: '/products/hp-i7-13th.jpg',
    blurb: "Portable 15,6 pouces récent, processeur 13e génération, idéal pour la bureautique avancée et le multitâche.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7-1355U (13e gén.)' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '15,6" Full HD' }] },
  { id: 'p34', name: 'HP 15 Core i7', cat: 'PC Portables', price: 560000, stock: 4, code: 'NGS-1047', image: '/products/hp-i7-silver.jpg',
    blurb: "Finition argentée, grand écran 15,6 pouces, bon compromis puissance et autonomie pour un usage quotidien.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7' }, { k: 'Mémoire', v: '16 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '15,6" Full HD' }] },
  { id: 'p35', name: 'HP Pavilion 15 Core i7', cat: 'PC Portables', price: 575000, stock: 5, code: 'NGS-1048', image: '/products/hp-pavilion-i7.jpg',
    blurb: "Châssis aluminium brossé, gabarit 15,6 pouces, adapté à la bureautique et à un usage créatif léger.",
    specs: [{ k: 'Processeur', v: 'Intel Core i7' }, { k: 'Mémoire', v: '16 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '15,6" Full HD' }] },
  { id: 'p36', name: 'HP Envy x360 Core i5 convertible', cat: 'PC Portables', price: 495000, stock: 4, code: 'NGS-1049', image: '/products/hp-envy-x360-i5.jpg',
    blurb: "Convertible tactile 360°, se transforme en tablette pour la prise de notes ou la présentation client.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '13,3" tactile convertible' }] },
  { id: 'p37', name: 'HP 14 Core i5', cat: 'PC Portables', price: 420000, stock: 7, code: 'NGS-1050', image: '/products/hp-14-i5.jpg',
    blurb: "Format compact 14 pouces, léger à transporter, pour les déplacements fréquents en clientèle.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Écran', v: '14" HD' }] },
  { id: 'p38', name: 'Lenovo ThinkPad E14 Gen 5 Core i5', cat: 'PC Portables', price: 465000, stock: 6, code: 'NGS-1051', image: '/products/lenovo-thinkpad-e14gen5-i5.jpg',
    blurb: "ThinkPad Gen 5 avec port USB-C, caméra HD 720p et dalle IPS, sous Windows 11 Pro.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5-1355U' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '14" IPS WUXGA' }] },
  { id: 'p39', name: 'HP 15 Core i5', cat: 'PC Portables', price: 410000, stock: 5, code: 'NGS-1052', image: '/products/hp-15-i5.jpg',
    blurb: "Modèle polyvalent 15,6 pouces pour la bureautique courante, navigation et outils de gestion.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Écran', v: '15,6" Full HD' }] },
  { id: 'p40', name: 'HP 15 Core i5 (gris)', cat: 'PC Portables', price: 415000, stock: 5, code: 'NGS-1053', image: '/products/hp-15-i5-gris.jpg',
    blurb: "Même gamme HP 15 en finition gris, stockage SSD plus généreux pour vos fichiers et logiciels métier.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '15,6" Full HD' }] },
  { id: 'p41', name: 'HP 15 Core i3 (noir)', cat: 'PC Portables', price: 345000, stock: 8, code: 'NGS-1054', image: '/products/hp-i3-noir.jpg',
    blurb: "Entrée de gamme fiable pour la bureautique de base, navigation web et messagerie.",
    specs: [{ k: 'Processeur', v: 'Intel Core i3' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '15,6" HD' }] },
  { id: 'p42', name: 'HP 15 Core i3 (argent)', cat: 'PC Portables', price: 340000, stock: 8, code: 'NGS-1055', image: '/products/hp-i3-argent.jpg',
    blurb: "Même configuration que la version noire, finition argentée, pour poste d'accueil ou de saisie.",
    specs: [{ k: 'Processeur', v: 'Intel Core i3' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '15,6" HD' }] },
  { id: 'p43', name: 'ASUS Vivobook 15 Core i3', cat: 'PC Portables', price: 335000, stock: 9, code: 'NGS-1056', image: '/products/asus-vivobook-i3.jpg',
    blurb: "Châssis fin et léger, écran NanoEdge, bon choix économique pour un usage bureautique quotidien.",
    specs: [{ k: 'Processeur', v: 'Intel Core i3' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 512 Go' }, { k: 'Écran', v: '15,6" Full HD' }] },
  { id: 'p44', name: 'Lenovo IdeaPad Ryzen 3', cat: 'PC Portables', price: 295000, stock: 10, code: 'NGS-1057', image: '/products/lenovo-ideapad-ryzen3.jpg',
    blurb: "Alternative AMD économique avec graphiques Radeon intégrés, pour la bureautique et le streaming vidéo.",
    specs: [{ k: 'Processeur', v: 'AMD Ryzen 3' }, { k: 'Graphiques', v: 'AMD Radeon intégré' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 256 Go' }] },
  { id: 'p45', name: 'HP 15 entrée de gamme', cat: 'PC Portables', price: 285000, stock: 10, code: 'NGS-1058', image: '/products/hp-15-entree-gamme.jpg',
    blurb: "Le modèle le plus accessible du catalogue, pour un premier équipement ou un poste de secours.",
    specs: [{ k: 'Processeur', v: 'Intel Core i3' }, { k: 'Mémoire', v: '4 Go' }, { k: 'Stockage', v: 'HDD 500 Go' }, { k: 'Écran', v: '15,6" HD' }] },
  { id: 'p46', name: 'Lenovo V15', cat: 'PC Portables', price: 245000, stock: 9, code: 'NGS-1059', image: '/products/lenovo-v15.jpg',
    blurb: "Portable Lenovo robuste et économique, grande capacité de stockage pour l'archivage local.",
    specs: [{ k: 'Processeur', v: 'Intel Core i3' }, { k: 'Mémoire', v: '4 Go' }, { k: 'Stockage', v: 'HDD 1 To' }, { k: 'Écran', v: '15,6" HD' }] },
  { id: 'p47', name: 'HP 15 — garantie atelier 12 mois', cat: 'PC Portables', price: 300000, stock: 8, code: 'NGS-1060', image: '/products/hp-15-garantie.jpg',
    blurb: "Portable HP 15 pouces vendu avec garantie atelier NG-Shop 12 mois incluse, contrôlé avant livraison.",
    specs: [{ k: 'Processeur', v: 'Intel Core i5' }, { k: 'Mémoire', v: '8 Go' }, { k: 'Stockage', v: 'SSD 256 Go' }, { k: 'Garantie', v: '12 mois atelier NG-Shop' }] },

  { id: 'p48', name: 'Souris Bluetooth & sans fil HP W10', cat: 'Composantes', price: 15000, stock: 20, code: 'NGS-3341', image: '/products/mouse-hp-w10.png',
    blurb: "Souris double mode Bluetooth et récepteur 2,4 GHz, rétroéclairage RGB, silencieuse au clic.",
    specs: [{ k: 'Connexion', v: 'Bluetooth + récepteur 2,4 GHz' }, { k: 'Boutons', v: '4' }, { k: 'Rétroéclairage', v: 'RGB' }] },
  { id: 'p49', name: 'Clé USB SanDisk Cruzer Blade 16 Go', cat: 'Composantes', price: 6000, stock: 30, code: 'NGS-3342', image: '/products/usb-sandisk-16go.jpg',
    blurb: "Clé USB 2.0 compacte et fiable pour le transfert de documents et de sauvegardes légères.",
    specs: [{ k: 'Capacité', v: '16 Go' }, { k: 'Interface', v: 'USB 2.0' }] },
  { id: 'p50', name: 'Clé USB SanDisk Cruzer Blade 64 Go', cat: 'Composantes', price: 14000, stock: 25, code: 'NGS-3343', image: '/products/usb-sandisk-64go.jpg',
    blurb: "Version grande capacité de la Cruzer Blade, pour stocker documents, photos et installateurs.",
    specs: [{ k: 'Capacité', v: '64 Go' }, { k: 'Interface', v: 'USB 2.0' }] },
  { id: 'p51', name: 'Mémoire DDR4 8 Go SO-DIMM Crucial', cat: 'Composantes', price: 32000, stock: 18, code: 'NGS-3344', image: '/products/ram-crucial-sodimm.jpg',
    blurb: "Barrette mémoire pour PC portable, upgrade simple pour fluidifier un poste ralenti.",
    specs: [{ k: 'Capacité', v: '8 Go' }, { k: 'Format', v: 'SO-DIMM (portable)' }, { k: 'Type', v: 'DDR4' }] },
  { id: 'p52', name: 'SSD M.2 PCIe Hikvision Desire 256 Go', cat: 'Composantes', price: 28000, stock: 15, code: 'NGS-3345', image: '/products/ssd-m2-hikvision.jpg',
    blurb: "SSD interne format M.2 PCIe, forte amélioration des temps de démarrage et de chargement.",
    specs: [{ k: 'Capacité', v: '256 Go' }, { k: 'Interface', v: 'M.2 PCIe' }] },
  { id: 'p53', name: 'SSD M.2 Target 256 Go', cat: 'Composantes', price: 26000, stock: 15, code: 'NGS-3346', image: '/products/ssd-m2-target.jpg',
    blurb: "SSD M.2 économique pour remplacer un disque dur mécanique et accélérer le poste.",
    specs: [{ k: 'Capacité', v: '256 Go' }, { k: 'Interface', v: 'M.2' }] },
  { id: 'p54', name: 'Mémoire DDR3 8 Go SO-DIMM Sesol', cat: 'Composantes', price: 18000, stock: 20, code: 'NGS-3347', image: '/products/ram-sesol-ddr3-sodimm.jpg',
    blurb: "Barrette DDR3 1600 MHz pour portables plus anciens, compatible avec la majorité des châssis DDR3.",
    specs: [{ k: 'Capacité', v: '8 Go' }, { k: 'Fréquence', v: '1600 MHz' }, { k: 'Format', v: 'SO-DIMM (portable)' }] },
  { id: 'p55', name: 'Mémoire DDR4 8 Go DIMM Crucial', cat: 'Composantes', price: 27000, stock: 20, code: 'NGS-3348', image: '/products/ram-crucial-dimm.jpg',
    blurb: "Barrette mémoire pour PC de bureau, upgrade fiable pour la bureautique multi-fenêtres.",
    specs: [{ k: 'Capacité', v: '8 Go' }, { k: 'Format', v: 'DIMM (bureau)' }, { k: 'Type', v: 'DDR4' }] },
  { id: 'p56', name: 'SSD SATA 2,5" Lexar 256 Go', cat: 'Composantes', price: 25000, stock: 15, code: 'NGS-3349', image: '/products/ssd-sata-lexar.jpg',
    blurb: "SSD SATA compatible avec la plupart des PC portables et bureaux équipés d'une baie 2,5 pouces.",
    specs: [{ k: 'Capacité', v: '256 Go' }, { k: 'Interface', v: 'SATA III' }] },
  { id: 'p57', name: 'SSD SATA 2,5" Ceamere 256 Go', cat: 'Composantes', price: 22000, stock: 15, code: 'NGS-3350', image: '/products/ssd-sata-ceamere.jpg',
    blurb: "SSD SATA économique pour remplacer un disque dur mécanique et gagner en réactivité.",
    specs: [{ k: 'Capacité', v: '256 Go' }, { k: 'Interface', v: 'SATA III' }] },

  { id: 'p58', name: 'Chargeur secteur Samsung 40W', cat: 'Composantes', price: 9000, stock: 25, code: 'NGS-3351', image: '/products/chargeur-samsung.jpg',
    blurb: "Chargeur compatible portables et tablettes Samsung, embouts 3,0 mm / 1,1 mm.",
    specs: [{ k: 'Puissance', v: '40 W' }, { k: 'Embout', v: '3,0 mm / 1,1 mm' }] },
  { id: 'p59', name: 'Chargeur MacBook 45W MagSafe 2', cat: 'Composantes', price: 18000, stock: 15, code: 'NGS-3352', image: '/products/chargeur-macbook-45w.jpg',
    blurb: "Chargeur compatible MacBook Air à connecteur MagSafe 2 (T-tip), prise EU incluse.",
    specs: [{ k: 'Puissance', v: '45 W' }, { k: 'Connecteur', v: 'MagSafe 2 (T-tip)' }] },
  { id: 'p60', name: 'Chargeur HP USB-C 65W', cat: 'Composantes', price: 14000, stock: 20, code: 'NGS-3353', image: '/products/chargeur-hp-usbc.jpg',
    blurb: "Chargeur USB-C compatible portables HP récents, câble renforcé avec attache velcro.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'USB-C' }] },
  { id: 'p61', name: 'Chargeur Lenovo USB-C 65W', cat: 'Composantes', price: 14000, stock: 20, code: 'NGS-3354', image: '/products/chargeur-lenovo-usbc.jpg',
    blurb: "Chargeur USB-C compatible ThinkPad et IdeaPad récents.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'USB-C' }] },
  { id: 'p62', name: 'Chargeur Dell embout rond 90W', cat: 'Composantes', price: 13000, stock: 20, code: 'NGS-3355', image: '/products/chargeur-dell-barrel.jpg',
    blurb: "Chargeur compatible gamme Dell Latitude et Inspiron à embout rond classique.",
    specs: [{ k: 'Puissance', v: '90 W' }, { k: 'Connecteur', v: 'Embout rond' }] },
  { id: 'p63', name: 'Chargeur Lenovo embout carré 65W', cat: 'Composantes', price: 12000, stock: 18, code: 'NGS-3356', image: '/products/chargeur-lenovo-slim.jpg',
    blurb: "Chargeur compatible ThinkPad à embout carré (slim tip), format compact.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'Embout carré slim' }] },
  { id: 'p64', name: 'Chargeur Dell USB-C 65W', cat: 'Composantes', price: 13500, stock: 18, code: 'NGS-3357', image: '/products/chargeur-dell-usbc.jpg',
    blurb: "Chargeur USB-C compatible gamme Dell Latitude et XPS récente.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'USB-C' }] },
  { id: 'p65', name: 'Chargeur Dell 65W embout rond', cat: 'Composantes', price: 11500, stock: 20, code: 'NGS-3358', image: '/products/chargeur-dell-65w.jpg',
    blurb: "Chargeur compatible gamme Dell Inspiron et Vostro, câble avec attache velcro.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'Embout rond' }] },
  { id: 'p66', name: 'Chargeur Acer 65W', cat: 'Composantes', price: 10500, stock: 18, code: 'NGS-3359', image: '/products/chargeur-acer.jpg',
    blurb: "Chargeur compatible gamme Acer Aspire et TravelMate, embout jaune.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'Embout rond jaune' }] },
  { id: 'p67', name: 'Chargeur HP embout large 65W', cat: 'Composantes', price: 11000, stock: 18, code: 'NGS-3360', image: '/products/chargeur-hp-rond.jpg',
    blurb: "Chargeur compatible anciens portables HP/Compaq à gros embout rond, adaptateur inclus.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'Embout rond large' }] },
  { id: 'p68', name: 'Chargeur Lenovo embout carré jaune 65W', cat: 'Composantes', price: 12000, stock: 18, code: 'NGS-3361', image: '/products/chargeur-lenovo-carre.jpg',
    blurb: "Chargeur compatible ThinkPad série récente à broche carrée jaune.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'Broche carrée jaune' }] },
  { id: 'p69', name: 'Chargeur ASUS 65W', cat: 'Composantes', price: 11500, stock: 18, code: 'NGS-3362', image: '/products/chargeur-asus.jpg',
    blurb: "Chargeur compatible gamme ASUS Vivobook et Zenbook, boîtier compact.",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'Embout rond' }] },
  { id: 'p70', name: 'Chargeur HP embout bleu 65W', cat: 'Composantes', price: 11000, stock: 20, code: 'NGS-3363', image: '/products/chargeur-hp-bleu.jpg',
    blurb: "Chargeur compatible gamme HP Pavilion et EliteBook à embout bleu \"smart pin\".",
    specs: [{ k: 'Puissance', v: '65 W' }, { k: 'Connecteur', v: 'Embout bleu' }] },
  { id: 'p71', name: 'Chargeur Lenovo compact 45W', cat: 'Composantes', price: 10500, stock: 18, code: 'NGS-3364', image: '/products/chargeur-lenovo-compact.jpg',
    blurb: "Chargeur compact compatible IdeaPad, boîtier carré avec prise EU intégrée.",
    specs: [{ k: 'Puissance', v: '45 W' }, { k: 'Connecteur', v: 'Embout rond' }] },

  { id: 'p72', name: 'Casque Bluetooth pliable P47', cat: 'Composantes', price: 12000, stock: 20, code: 'NGS-3365', image: '/products/casque-p47-bluetooth.jpg',
    blurb: "Casque sans fil pliable, commandes tactiles sur l'oreillette, autonomie prolongée.",
    specs: [{ k: 'Connexion', v: 'Bluetooth 4.2' }, { k: 'Format', v: 'Pliable, arceau réglable' }] },
  { id: 'p73', name: 'Casque circum-aural sans fil Studio Max', cat: 'Composantes', price: 45000, stock: 8, code: 'NGS-3366', image: '/products/casque-studio-max.jpg',
    blurb: "Casque premium circum-aural, coussinets mémoire de forme, idéal appels et musique.",
    specs: [{ k: 'Connexion', v: 'Bluetooth' }, { k: 'Format', v: 'Circum-aural' }] },
  { id: 'p74', name: 'Adaptateur USB 3.0 vers Ethernet Gigabit', cat: 'Réseaux', price: 8000, stock: 20, code: 'NGS-3367', image: '/products/adaptateur-usb-ethernet.jpg',
    blurb: "Ajoute un port réseau filaire Gigabit à un portable qui n'en dispose pas.",
    specs: [{ k: 'Interface', v: 'USB 3.0' }, { k: 'Réseau', v: 'Gigabit Ethernet' }] },
  { id: 'p75', name: 'Hub USB-C 6-en-1 (HDMI, PD, SD, TF)', cat: 'Composantes', price: 15000, stock: 15, code: 'NGS-3368', image: '/products/hub-usbc-6in1.jpg',
    blurb: "Station compacte pour étendre un portable USB-C : HDMI, charge PD, USB-A et lecteur de cartes.",
    specs: [{ k: 'Ports', v: 'HDMI, 2× USB-A, PD, SD, microSD' }] },

  { id: 'p76', name: 'Clavier + souris sans fil Logitech MK235', cat: 'Composantes', price: 22000, stock: 12, code: 'NGS-3369', image: '/products/clavier-souris-logitech-mk235.jpg',
    blurb: "Pack clavier et souris sans fil, récepteur unifié, autonomie longue durée.",
    specs: [{ k: 'Connexion', v: 'Sans fil 2,4 GHz' }, { k: 'Contenu', v: 'Clavier + souris' }] },
  { id: 'p77', name: 'Clavier silicone flexible USB', cat: 'Composantes', price: 9000, stock: 15, code: 'NGS-3370', image: '/products/clavier-silicone-flexible.jpg',
    blurb: "Clavier souple et étanche, s'enroule pour le transport, idéal environnement atelier.",
    specs: [{ k: 'Connexion', v: 'USB filaire' }, { k: 'Matériau', v: 'Silicone souple' }] },
  { id: 'p78', name: 'Souris sans fil HP 510A', cat: 'Composantes', price: 8000, stock: 20, code: 'NGS-3371', image: '/products/souris-hp-510a.jpg',
    blurb: "Souris sans fil compacte avec récepteur USB, précision fiable pour un usage bureautique.",
    specs: [{ k: 'Connexion', v: 'Sans fil 2,4 GHz' }, { k: 'Boutons', v: '3' }] },
  { id: 'p79', name: 'Clavier filaire HP K1600', cat: 'Composantes', price: 10000, stock: 20, code: 'NGS-3372', image: '/products/clavier-hp-k1600.jpg',
    blurb: "Clavier filaire complet avec pavé numérique, disposition standard, connexion USB.",
    specs: [{ k: 'Connexion', v: 'USB filaire' }, { k: 'Format', v: 'Complet avec pavé numérique' }] },
  { id: 'p80', name: 'Souris filaire USB basique', cat: 'Composantes', price: 3500, stock: 30, code: 'NGS-3373', image: '/products/souris-usb-basique.jpg',
    blurb: "Souris filaire d'appoint économique, idéale en dépannage ou poste secondaire.",
    specs: [{ k: 'Connexion', v: 'USB filaire' }, { k: 'Boutons', v: '3' }] },
  { id: 'p81', name: 'Souris sans fil HP S1000', cat: 'Composantes', price: 9500, stock: 20, code: 'NGS-3374', image: '/products/souris-hp-s1000.jpg',
    blurb: "Souris sans fil silencieuse, molette de défilement précise, format compact.",
    specs: [{ k: 'Connexion', v: 'Sans fil 2,4 GHz' }, { k: 'Boutons', v: '3' }] },

  { id: 'p82', name: 'Batterie compatible Toshiba Satellite', cat: 'Composantes', price: 20000, stock: 10, code: 'NGS-3375', image: '/products/batterie-toshiba.jpg',
    blurb: "Batterie de remplacement compatible gamme Toshiba Satellite, 6 cellules.",
    specs: [{ k: 'Cellules', v: '6' }, { k: 'Compatibilité', v: 'Toshiba Satellite' }] },
  { id: 'p83', name: 'Batterie compatible HP longue durée', cat: 'Composantes', price: 24000, stock: 10, code: 'NGS-3376', image: '/products/batterie-hp-longue.jpg',
    blurb: "Batterie longue autonomie compatible portables HP, format fin 8 cellules.",
    specs: [{ k: 'Cellules', v: '8' }, { k: 'Compatibilité', v: 'HP' }] },
  { id: 'p84', name: 'Batterie compatible Acer Aspire One', cat: 'Composantes', price: 18000, stock: 10, code: 'NGS-3377', image: '/products/batterie-acer.jpg',
    blurb: "Batterie de remplacement compatible gamme Acer Aspire One, 6 cellules.",
    specs: [{ k: 'Cellules', v: '6' }, { k: 'Compatibilité', v: 'Acer Aspire One' }] },
  { id: 'p85', name: 'Batterie compatible HP ProBook (4 cellules)', cat: 'Composantes', price: 16000, stock: 12, code: 'NGS-3378', image: '/products/batterie-hp-probook-4c.jpg',
    blurb: "Batterie de remplacement compatible gamme HP ProBook, format compact 4 cellules.",
    specs: [{ k: 'Cellules', v: '4' }, { k: 'Compatibilité', v: 'HP ProBook' }] },
  { id: 'p86', name: 'Batterie compatible HP Pavilion', cat: 'Composantes', price: 19000, stock: 12, code: 'NGS-3379', image: '/products/batterie-hp-pavilion.jpg',
    blurb: "Batterie de remplacement compatible gamme HP Pavilion / Compaq, 6 cellules.",
    specs: [{ k: 'Cellules', v: '6' }, { k: 'Compatibilité', v: 'HP Pavilion / Compaq' }] },
  { id: 'p87', name: 'Batterie compatible HP EliteBook (interne)', cat: 'Composantes', price: 22000, stock: 8, code: 'NGS-3380', image: '/products/batterie-hp-elitebook.jpg',
    blurb: "Batterie interne fine compatible gamme HP EliteBook, pose atelier recommandée.",
    specs: [{ k: 'Type', v: 'Interne' }, { k: 'Compatibilité', v: 'HP EliteBook' }] },
  { id: 'p88', name: 'Batterie compatible Lenovo ThinkPad SL/L', cat: 'Composantes', price: 21000, stock: 8, code: 'NGS-3381', image: '/products/batterie-lenovo-thinkpad.jpg',
    blurb: "Batterie de remplacement compatible séries ThinkPad SL et L, bonne autonomie.",
    specs: [{ k: 'Cellules', v: '6' }, { k: 'Compatibilité', v: 'Lenovo ThinkPad SL/L' }] },
  { id: 'p89', name: 'Batterie compatible HP ProBook 4x30', cat: 'Composantes', price: 17000, stock: 10, code: 'NGS-3382', image: '/products/batterie-hp-probook-4x30.jpg',
    blurb: "Batterie de remplacement compatible série HP ProBook 4x30, 6 cellules.",
    specs: [{ k: 'Cellules', v: '6' }, { k: 'Compatibilité', v: 'HP ProBook 4x30' }] },
  { id: 'p90', name: 'Batterie compatible HP/Compaq Business', cat: 'Composantes', price: 18000, stock: 10, code: 'NGS-3383', image: '/products/batterie-hp-compaq.jpg',
    blurb: "Batterie de remplacement compatible portables professionnels HP/Compaq.",
    specs: [{ k: 'Cellules', v: '6' }, { k: 'Compatibilité', v: 'HP / Compaq Business' }] },
  { id: 'p91', name: 'Batterie compatible générique (4 cellules)', cat: 'Composantes', price: 15000, stock: 12, code: 'NGS-3384', image: '/products/batterie-generique.jpg',
    blurb: "Batterie de remplacement fine et légère, plusieurs compatibilités selon modèle.",
    specs: [{ k: 'Cellules', v: '4' }, { k: 'Compatibilité', v: 'Multi-marques (à vérifier)' }] },
  { id: 'p92', name: 'Batterie compatible Dell/Sony fine', cat: 'Composantes', price: 23000, stock: 8, code: 'NGS-3385', image: '/products/batterie-dell-slim.jpg',
    blurb: "Batterie fine format argenté compatible portables Dell et Sony, connecteur latéral.",
    specs: [{ k: 'Type', v: 'Fine, connecteur latéral' }, { k: 'Compatibilité', v: 'Dell / Sony' }] }
];

export const SERVICES = [
  { name: 'Diagnostic à distance', desc: "Prise en main du poste, rapport écrit sous 24 h.", price: 5000 },
  { name: 'Intervention sur site', desc: "Déplacement Abidjan inclus, une heure d'atelier sur place.", price: 15000 },
  { name: 'Réinstallation système', desc: "Windows, pilotes, bureautique, sauvegarde des données.", price: 12000 },
  { name: 'Contrat PME mensuel', desc: "Jusqu'à 15 postes supervisés, priorité 4 h.", price: 45000 }
];

export const STEPS = [
  { label: 'Reçu en atelier', when: '24 août, 09:40' },
  { label: 'Diagnostic', when: '24 août, 15:10' },
  { label: 'Réparation', when: '26 août, 08:30' },
  { label: 'Contrôle qualité', when: 'estimé 26 août' },
  { label: 'Prêt à retirer', when: '—' }
];

export const LOG = [
  { when: '26 août, 08:30', title: 'Remplacement de l’alimentation', body: "Bloc 300 W neuf posé, câblage refait, poste en test de charge depuis 45 minutes." },
  { when: '25 août, 11:05', title: 'Devis validé par le client', body: "Accord SMS d’Estelle Koffi. Pièce sortie du stock atelier (réf. NGS-9004)." },
  { when: '24 août, 15:10', title: 'Diagnostic terminé', body: "Coupures sous charge dues à l’alimentation ; ventilateur processeur empoussiéré. Disque et mémoire sains." },
  { when: '24 août, 09:40', title: 'Réception en atelier', body: "Unité centrale déposée par le client avec cordon secteur. Étiquette NG-M-2481 apposée." }
];

export const REPAIR_QUOTE = [
  { label: 'Alimentation 300 W (pièce)', amount: '28 000 FCFA' },
  { label: 'Nettoyage & pâte thermique', amount: '6 000 FCFA' },
  { label: "Main-d'œuvre atelier (1,5 h)", amount: '15 000 FCFA' }
];

export const NAV = [
  { id: 'boutique', label: 'Boutique', roles: ['Client', 'Technicien', 'Gérant'] },
  { id: 'panier', label: 'Panier', roles: ['Client', 'Gérant'] },
  { id: 'maintenance', label: 'Maintenance', roles: ['Client', 'Technicien', 'Gérant'] },
  { id: 'suivi', label: 'Suivi réparation', roles: ['Client', 'Technicien', 'Gérant'] },
  { id: 'caisse', label: 'Caisse', roles: ['Technicien', 'Gérant'] },
  { id: 'dashboard', label: 'Tableau de bord', roles: ['Gérant'] },
  { id: 'compte', label: 'Compte', roles: ['Client', 'Technicien', 'Gérant'] }
];

export const PAYMENTS = [
  { id: 'Orange Money', note: 'USSD #150#' },
  { id: 'MTN MoMo', note: 'Marchand 6 7712' },
  { id: 'Espèces', note: 'Ticket imprimé' },
  { id: 'Virement bancaire', note: 'Compte entreprise' }
];

export const COMMUNES = [
  'Abobo', 'Adjamé', 'Anyama', 'Attécoubé', 'Bingerville', 'Cocody',
  'Koumassi', 'Marcory', 'Plateau', 'Port-Bouët', 'Songon', 'Treichville', 'Yopougon'
];

export const INTER_TYPES = ['À distance', 'Sur site', 'Dépôt en boutique'];
export const SLOTS = ["Aujourd’hui 16 h", 'Jeudi matin', 'Jeudi après-midi', 'Samedi matin'];

export const KPIS = [
  { value: '1 245 000', label: 'Ventes du jour · FCFA', delta: '+18 % vs mardi · 11 tickets de caisse' },
  { value: '12', label: 'Tickets de maintenance ouverts', delta: '3 en attente de pièce, 2 prêts à retirer' },
  { value: '23 %', label: 'Marge moyenne matériel', delta: 'Composants 31 % · portables 14 %' }
];

export const SALES = [
  { ref: 'NG-C-3388', client: 'Cabinet Koffi & Fils', canal: 'Devis PME', amount: '612 000 FCFA' },
  { ref: 'NG-T-1902', client: 'Comptoir Plateau', canal: 'Caisse', amount: '96 000 FCFA' },
  { ref: 'NG-C-3387', client: 'Lycée Bilingue Cocody', canal: 'Boutique en ligne', amount: '284 000 FCFA' },
  { ref: 'NG-T-1901', client: 'Client de passage', canal: 'Caisse', amount: '34 000 FCFA' },
  { ref: 'NG-M-2477', client: 'Pharmacie Cocody', canal: 'Maintenance', amount: '49 000 FCFA' }
];

export const LOW_STOCK_IDS = ['p3', 'p7', 'p2'];

export const HISTORY = [
  { ref: 'NG-C-3388', date: '24 août 2026', status: 'Payée', amount: '612 000 FCFA' },
  { ref: 'NG-M-2481', date: '24 août 2026', status: 'En atelier', amount: '49 000 FCFA' },
  { ref: 'NG-C-3341', date: '02 août 2026', status: 'Payée', amount: '145 000 FCFA' },
  { ref: 'NG-C-3288', date: '17 juillet 2026', status: 'Échéance 15 j', amount: '310 000 FCFA' }
];

export const PARC = [
  { name: '6 × Dell OptiPlex 7010', detail: 'Postes comptabilité et accueil · sous contrat', tag: 'Supervisé', ok: true },
  { name: '2 × HP LaserJet M211d', detail: 'Toner commandé le 20 août', tag: 'À surveiller', ok: false },
  { name: 'Baie réseau Cocody', detail: 'Switch 24 ports + routeur AX23', tag: 'Supervisé', ok: true }
];

export const ACCOUNT_USERS = [
  { name: 'Estelle Koffi', role: 'Administratrice' },
  { name: 'Joseph Kouassi', role: 'Achats — peut commander' },
  { name: 'Aliou N. (NG-Shop)', role: 'Technicien assigné' }
];

export function fmt(n) {
  return n.toLocaleString('fr-FR').replace(/[  ]/g, ' ') + ' FCFA';
}

export function stockOf(p) {
  if (p.stock === 0) return { label: 'Rupture', tone: 'danger' };
  if (p.stock <= 4) return { label: p.stock + ' en stock', tone: 'danger' };
  return { label: p.stock + ' en stock', tone: 'ok' };
}

export function cartTotal(cart) {
  return Object.keys(cart).reduce((a, id) => {
    const p = PRODUCTS.find((x) => x.id === id);
    return a + (p ? p.price * cart[id] : 0);
  }, 0);
}

// Réduction d'affichage (façon "prix barré" marketplace) : générée de façon
// déterministe à partir de l'id produit, pas de vraie promotion en base.
export function discountOf(p) {
  let hash = 0;
  for (let i = 0; i < p.id.length; i++) hash = (hash * 31 + p.id.charCodeAt(i)) >>> 0;
  const percent = 15 + (hash % 16); // 15 à 30 %
  const oldPrice = Math.round(p.price / (1 - percent / 100) / 100) * 100;
  return { percent, oldPrice };
}

export const CATEGORY_ICONS = {
  'PC Portables': '💻',
  'PC Bureaux': '🖥️',
  'Composantes': '🧩',
  'Imprimantes': '🖨️',
  'Réseaux': '📶',
  'Téléphones & Tablettes': '📱',
  'Électroménager': '🔌',
  'Gaming': '🎮',
  'TV & Audio': '📺'
};
